source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'mime-types', '>= 1.25.1'
# Image Science requires FreeImage:
#   brew install freeimage
#   apt-get install libfreeimage-dev
#   yum install freeimage-devel
#   etc...
gem 'image_science', '>= 1.2.6'
gem 'aws-sdk'
gem 'fakes3'

# Normally, you'd include the following line in your Gemfile. But for the purposes of
# developing this gem, we prefer to autoload the source files. See config/application.rb
# wherein we do that.
# gem 'echo_uploads'

group :test do
  gem 'turn'
  gem 'minitest-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'timecop'
end