language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
gemfile:
  - example/gemfiles/rails-4.gemfile
  - example/gemfiles/rails-5.0.gemfile
  - example/gemfiles/rails-5.gemfile
script: cd example && rails test